pipeline {
    agent any
    environment {
        DOCKER_IMAGE = "akwasi84/ecommerce-app" 
    }
    stages {
        stage('Fetch Code') {
            steps { checkout scm }
        }
        stage('Build Image') {
            steps {
                sh "docker build -t ${DOCKER_IMAGE}:latest ."
            }
        }
        stage('Login & Push') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'docker-hub-creds', passwordVariable: 'PASS', usernameVariable: 'USER')]) {
                    sh "echo $PASS | docker login -u $USER --password-stdin"
                    sh "docker push ${DOCKER_IMAGE}:latest"
                }
            }
        }
        stage('Deploy Locally') {
            steps {
                // Stop old version if running, then start new one
                sh "docker stop ecommerce-container || true"
                sh "docker rm ecommerce-container || true"
                sh "docker run -d -p 8081:80 --name ecommerce-container ${DOCKER_IMAGE}:latest"
            }
        }
    }
}
