pipeline {
    agent any

    stages {

        stage('Build Docker Image') {
            steps {
                dir('flask-cicd-project') {
                    sh 'docker build -t flask-app .'
                }
            }
        }

        stage('Stop Old Container') {
            steps {
                sh 'docker stop flask-container || true'
                sh 'docker rm flask-container || true'
            }
        }

        stage('Run Container') {
            steps {
                sh 'docker run -d -p 5000:5000 --name flask-container flask-app'
            }
        }

    }
}
